name: Pipeline

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: ./gradlew clean test --stacktrace --info

  build:
    needs: [setup, test]
    runs-on: ubuntu-latest

    steps:
      - name: Build mod
        run: ./gradlew build -x test --stacktrace --info

      - name: Upload mod jars
        uses: actions/upload-artifact@v4
        with:
          name: DeepEchoes-build
          path: |
            build/libs/*.jar